### ISSUE TITLE
Issue: Odd border lines

### ISSUE THREAD

**Issue by qualiall** [Wayzware/UnlockAllTilesMod#4]
Not even sure if it's your mod causing it, but I see these strange border dashes on my map.  I am able to build on it no issue.  Just not sure why it looks like I hadn't bought those tiles
![20231221090338_1](https://github.com/Wayzware/UnlockAllTilesMod/assets/95945450/b56b9c38-069e-453e-a128-e71d4e31f233)

**Comment by Wayzware** [comment]
Hello,
Could you try removing my mod and see if the problem still exists? (Your save will be fine)

If it still happens without my mod, can you post the map/save here for me to investigate further?

**Comment by qualiall** [comment]
Thank you.  I removed the mod and the lines were still there.  Here is the save
https://drive.google.com/drive/folders/1MBUWAqvYwcv-Jb6ti7L-eJJYyrvgKOKV?usp=sharing
Map is called "New York City"
https://www.nexusmods.com/citiesskylines2/mods/34

**Comment by Wayzware** [comment]
Since the lines are still there without my mod being installed, I would encourage you to check with the map author for a solution to this.

Marking as closed. If you find that this issue occurs with my mod installed, please create a new issue. 
Thanks :)
